config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resource :cart, only: [:show, :destroy] do
    collection do
      # /cart/2/add
      post :add, path: ':id/add'
      get :checkout
    end
  end

  resources :orders, only: [:index, :show, :create] do
    member do
      put :cancel # PUT /orders/2/cancel
      get :pay
      post :paid
    end
  end

resources :books, only: [:index, :show] do
    member do
      post :comment # POST /books/:id/comment, to 'books#comment'
    end
  end

  resources :publishers, only: [:show]
  resources :categories, only: [:show]
  
  namespace :api do
    resources :books, only: [] do
      member do
        post :favorite # /api/books/:id/favorite
      end
    end
  end

  root 'books#index'

  namespace :admin do
    resources :publishers
    resources :categories
    resources :books # /admin/books
    root 'books#index' # /admin/
  end
end

app/views/shared/frontend/_menu.html.erb
<aside class="menu">
 <p class="menu-label">
    分類
  </p>
  <ul class="menu-list">
    <% categories.each do |category| %>
      <li>
        <%= link_to category.name, category %>
      </li>
    <% end %>
  </ul>

  <p class="menu-label">
    出版社
  </p>
  <ul class="menu-list">
    <% publishers.each do |publisher| %>
      <%= link_to publisher.name, publisher %>
    <% end %>
  </ul>
</aside>

app/views/shared/frontend/_model.html.erb
<div class="modal" id="message-window">
  <div class="modal-background"></div>
  <div class="modal-content">
    <article class="message is-dark">
      <div class="message-body" id="message-content"></div>
    </article>
  </div>
  <button class="modal-close is-large" aria-label="close"></button>
</div>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <i class="fas fa-book fa-2x"></i>
    <% end %>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to '書本連結', books_path, class: 'navbar-item' %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item" data-controller="cart" data-action="ajax:success@window->cart#update">
        <div class="buttons">
          <%= link_to cart_path, class: 'button' do %>
            <i class="fas fa-shopping-cart"></i>(<span data-target="cart.items"><%= current_cart.items.count %></span>)
          <% end %>
          <% if user_signed_in? %>
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                <%= current_user.email %>
              </a>

              <div class="navbar-dropdown">
                <a class="navbar-item">
                  <%= link_to '訂單', orders_path, class: 'button' %>
                </a>
                <a class="navbar-item">
                  Jobs
                </a>
                <a class="navbar-item">
                  Contact
                </a>
                <hr class="navbar-divider">
                <a class="navbar-item">
                  <%= link_to '登出', destroy_user_session_path, class: 'button is-light', method: :delete %>
                </a>
              </div>
            </div>
        </div>
      <% else %>
        <%= link_to '註冊', new_user_registration_path, class: 'button is-primary' %>
        <%= link_to '登入', new_user_session_path, class: 'button is-light' %>
      <% end %>
      </div>
    </div>
  </div>
  </div>
</nav>