config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resource :cart, only: [:show, :destroy] do
    collection do
      # /cart/2/add
      post :add, path: ':id/add'
      get :checkout
    end
  end

  resources :orders, only: [:index, :show, :create] do
    member do
      put :cancel # PUT /orders/2/cancel
      get :pay
      post :paid
    end
  end

resources :books, only: [:index, :show] do
    member do
      post :comment # POST /books/:id/comment, to 'books#comment'
    end
  end

  resources :publishers, only: [:show]
  resources :categories, only: [:show]
  
  namespace :api do
    resources :books, only: [] do
      member do
        post :favorite # /api/books/:id/favorite
      end
    end
  end

  root 'books#index'

  namespace :admin do
    resources :publishers
    resources :categories
    resources :books # /admin/books
    root 'books#index' # /admin/
  end
end

app/models/book.rb
class Book < ApplicationRecord
  acts_as_paranoid

  #validations
  validates :title,:published_at, presence: true
  validates :isbn, :isbn13, presence: true, uniqueness: true 
  validates :list_price, :sell_price, :page_num, numericality: { greater_than: 0 }

  # relationships
  belongs_to :publisher # publisher_id
  belongs_to :category
  has_one_attached :cover_image
  has_many :comments
  has_many :favorites
  has_many :users, through: :favorites

  # scopes
  scope :available, -> { where(on_sell: true).where('list_price > 0') }

  def favorited_by?(u)
    favorites.exists?(user: u)
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::BaseController
  before_action :find_book, only: [:show, :edit, :update, :destroy]

  def index
    # @books = Book.where(on_sell: true).with_attached_cover_image
    @books = Book.available.with_attached_cover_image.page(params[:page]).per(6)
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to admin_books_path, notice: "新增書本成功"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to edit_admin_book_path(@book.id), notice: '更新成功'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to admin_books_path, notice: '資料已刪除'
  end

  private

  def find_book
    @book = Book.find(params[:id])
  end

  def book_params
    # strong parameters
    params.require(:book).permit(:title,
                                 :description,
                                 :list_price,
                                 :sell_price,
                                 :page_num,
                                 :isbn,
                                 :isbn13,
                                 :cover_image,
                                 :on_sell,
                                 :published_at,
                                 :publisher_id,
                                 :category_id)
  end
end

app/controllers/api/books_controller.rb
class Api::BooksController < ApplicationController
  before_action :login_check?
  
  def favorite
    book = Book.find(params[:id])
    
    fav = Favorite.find_by(user: current_user, book: book)
    # fav = Book.favorites.find_by(user: current_user)
    # fav = current_user.favorites.find_by(book: book)
    
    favorited = false
    
    if fav
      fav.destroy
      favorited = false
    else
      current_user.favorites.create(book: book)
      favorited = true
    end

    render json: {status: 'ok', favorited: favorited}
  end

  private
  def login_check?
    if not user_signed_in?
      head 401
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :comment]
  layout 'book'

  def index
    @books = Book.available.with_attached_cover_image.page(params[:page]).per(6)
    @publishers = Publisher.available
  end

  def show
    @comment = Comment.new
    @comments = @book.comments.order(id: :desc)
  end

  def comment
    # comment 角度
    # @comment = Comment.new(comment_params, user: current_user, book: @book)
    
    # book 角度
    @comment = @book.comments.build(comment_params)

    # user 角度
    # @comment = current_user.comments.build(comment_params, book: @book)

    if @comment.save
      # render :comment
      respond_to do |format|
        format.js { render 'comment' }
      end
      # redirect_to @book, notice: '留言成功'
    else
      render js: 'alert("發生錯誤");'
    end
  end

  private
  def find_book
    @book = Book.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:title, :content).merge(user: current_user)
  end
end

app/helpers/book_helper.rb
module BookHelper
  def cover_image_tag(book, width: 800, height: 600, dummy_img: false)

    if dummy_img
      if book.cover_image.attached?
        image_tag book.cover_image.variant(resize_to_limit: [width, height])
      else
         image_tag "https://bulma.io/images/placeholders/1280x960.png"
      end
    else
      image_tag book.cover_image.variant(resize_to_limit: [width, height]) if book.cover_image.attached?
    end

    # private
    # def generate_cover_image(width, height)
    #   image_tag book.cover_image.variant(resize_to_limit: [width, height])
    # end
  end
end

app/views/admin/books/_form.html.erb
<% if book.errors.any? %>
  <ul>
    <% book.errors.full_messages.each do |message|  %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for([:admin, book]) do |form| %>

  <div class="field">
    <%= form.label :cover_image, '封面', class: 'label'%>
    <%= form.file_field :cover_image, class: 'input' %>
    <%= cover_image_tag book, width: 300, height: 300 %>
  </div>

  <div class="columns">
    <div class="column is-4">
      <div class="field">
        <%= form.label :title, '標題', class: 'label'%>
        <%= form.text_field :title, class: 'input' %>
      </div>
    </div>

    <div class="column is-4">
      <div class="field">
        <%= form.label :publisher_id, '出版社', class: 'label'%>
        <div class="select is-fullwidth">
          <%= form.collection_select :publisher_id, Publisher.available, :id, :name %>
        </div>
      </div>
    </div>

    <div class="column is-4">
      <div class="field">
        <%= form.label :category_id, '分類', class: 'label' %>
        <div class="select is-fullwidth">
          <%= form.collection_select :category_id, Category.all, :id, :name %>
        </div>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :description, '內容', class: 'label' %>
    <%= form.text_area :description, class: 'textarea' %>
  </div>

  <div class="columns">
    <div class="column field">
      <%= form.label :list_price, '售價' , class: 'label' %>
      <%= form.number_field :list_price, class: 'input' %>
    </div>
    
    <div class="column field">
      <%= form.label :sell_price, '特價', class: 'label' %>
      <%= form.number_field :sell_price, class: 'input' %>
    </div>

    <div class="column field">
      <%= form.label :page_num, '頁數', class: 'label' %>
      <%= form.number_field :page_num, class: 'input' %>
    </div>
  </div>

  <div class="columns">
    <div class="column">
      <div class="field">
        <%= form.label :isbn, 'ISBN',class: 'label' %>
        <%= form.text_field :isbn, class: 'input' %>
      </div>
    </div>

    <div class="column">
      <div class="field">
        <%= form.label :isbn13, 'ISBN-13', class: 'label' %>
        <%= form.text_field :isbn13, class: 'input' %>
      </div>
    </div>

    <div class="column">
      <div class="field">
        <%= form.label :published_at, '上架日期', class: 'label' %>
        <%= form.date_field :published_at, class: 'input', data: { controller: "datepicker" } %>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.check_box :on_sell, class: 'checkbox'%>
    <%= form.label :on_sell, '是否上架?' %>
  </div>

  <div class="field">
    <%= form.submit class: 'button' %>
  </div>
<% end %>

<%# <%= javascript_pack_tag 'datepicker' %>

app/views/admin/books/edit.html.erb
<h1 class="title"><i class="fas fa-edit"></i> 編輯書本： <%= @book.title %></h1>

<%= render 'form', book: @book %>

app/views/admin/books/index.html.erb
<div class="columns">
  <div class="column is-2">
    <aside class="menu">
      <p class="menu-label">
        分類
      </p>
      <ul class="menu-list">
        <li><a>Web 技術</a></li>
        <li><a>版本控制</a></li>
        <li><a>資料庫</a></li>
      </ul>

      <p class="menu-label">
        出版社
      </p>
      <ul class="menu-list">
        <li><a>Ruby</a></li>
        <li><a>Hello World</a></li>
      </ul>
    </aside>
  </div>

  <div class="column is-10">
    <h1 class="title"><i class="fas fa-book"></i> 書本列表</h1>

    <%= link_to(new_admin_book_path, class: 'button is-primary') do %>
      <span class="icon">
        <i class="fas fa-plus"></i>
      </span>
      <span>新增書本</span>
    <% end %>

    <div class="columns is-multiline">
      <% @books.each do |book| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= cover_image_tag book, width: 300, height: 300, dummy_img: true %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                  </figure>
                </div>
                <div class="media-content">
                  <p class="title is-4"><%= link_to book.title, book_path(book.id) %></p>
                  <p class="subtitle is-6">@johnsmith</p>
                </div>
              </div>

              <div class="content">
                <time datetime="2016-1-1">上架日期：<%= book.published_at %></time>
              </div>
            </div>

            <div class="card-footer">
              <div class="card-footer-item">
                <%= link_to 'Edit', edit_admin_book_path(book.id), class: 'button' %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate @books %>
  </div>
</div>

app/views/admin/books/new.html.erb
<h1 class="title"><i class="fas fa-plus"></i> 新增書本</h1>

<%= render 'form', book: @book %>

app/views/admin/books/show.html.erb
<h1 class="title">書名：<%= @book.title %></h1>