config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resource :cart, only: [:show, :destroy] do
    collection do
      # /cart/2/add
      post :add, path: ':id/add'
      get :checkout
    end
  end

  resources :orders, only: [:index, :show, :create] do
    member do
      put :cancel # PUT /orders/2/cancel
      get :pay
      post :paid
    end
  end

resources :books, only: [:index, :show] do
    member do
      post :comment # POST /books/:id/comment, to 'books#comment'
    end
  end

  resources :publishers, only: [:show]
  resources :categories, only: [:show]
  
  namespace :api do
    resources :books, only: [] do
      member do
        post :favorite # /api/books/:id/favorite
      end
    end
  end

  root 'books#index'

  namespace :admin do
    resources :publishers
    resources :categories
    resources :books # /admin/books
    root 'books#index' # /admin/
  end
end

app/models/cart.rb
class Cart
  attr_reader :items

  def initialize(items = [])
    @items = items
  end

  def add_item(product_id)
    found_item = @items.find { |item| item.product_id == product_id }

    if found_item
      found_item.increment!
    else
      @items << CartItem.new(product_id)
    end
  end

  def empty?
    @items.empty?
  end

  def total_price
    @items.reduce(0) { |total, item| total + item.total_price }
  end

  def serialize
    result = @items.map { |item|
      { "product_id" => item.product_id, "quantity" => item.quantity }
    }

    { "items" => result }
  end

  def self.from_hash(hash = nil)
    # cart_hash = {
    #   "items" => [
    #     { "product_id" => 1, "quantity" => 3 },
    #     { "product_id" => 2, "quantity" => 2 }
    #   ]
    # }

    if hash && hash["items"]
      # 還原
      items = hash["items"].map { |item|
        CartItem.new(item["product_id"], item["quantity"])
      }
      new(items)
    else
      # 新車
      new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:checkout]

  def add
    current_cart.add_item(params[:id])
    session['cart9527'] = current_cart.serialize

    # redirect_to root_path, notice: '成功加入購物車'
    render json: {items: current_cart.items.count}
  end

  def show
  end

  def checkout
    @order = Order.new
  end

  def destroy
    session['cart9527'] = nil

    redirect_to root_path, notice: '已清空購物車'
  end
end

app/views/carts/_cart.html.erb
<% if cart.empty? %>
  <article class="message is-dark">
    <div class="message-body">
      目前購物車是空的喔！
    </div>
  </article>
<% else %>
<table class="table is-fullwidth">
  <thead>
    <tr>
      <th>商品名稱</th>
      <th>數量</th>
      <th>單價</th>
      <th>小計</th>
    </tr>
  </thead>
  <tbody>
    <% cart.items.each do |item|  %>
      <tr>
        <td><%= item.product.title %></td>
        <td><%= item.quantity %></td>
        <td><%= item.product.sell_price %></td>
        <td><%= item.total_price %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="4">
        總價：<%= cart.total_price %>
      </td>
    </tr>
  </tfoot>
</table>
<% end %>

app/views/carts/checkout.html.erb
<h1 class="title">結帳</h1>

<%= render 'cart', cart: current_cart %>

<%= form_with(model: @order) do |form| %>
  <div clas="field">
    <%= form.label :recipient, '收件人', class: 'label' %>
    <%= form.text_field :recipient, class: 'input' %>
  </div>
  
  <div clas="field">
    <%= form.label :tel, '電話', class: 'label' %>
    <%= form.text_field :tel, class: 'input' %>
  </div>

  <div clas="field">
    <%= form.label :address, '地址', class: 'label' %>
    <%= form.text_field :address, class: 'input' %>
  </div>

  <div clas="field">
    <%= form.label :note, '說明', class: 'label' %>
    <%= form.text_area :note, class: 'textarea' %>
  </div>

  <div clas="field">
    <%= form.submit '確認', class: 'button is-primary' %>
  </div>

<% end %>

app/views/carts/show.html.erb
<h1 class="title"><i class="fas fa-shopping-cart"></i> 購物車</h1>

<%= link_to '清空購物車', cart_path, method: :delete, class: 'button is-small is-light' unless current_cart.empty? %>

<%= render 'cart', cart: current_cart%>

<%= link_to '繼續選購', root_path, class: 'button is-primary' %>
<%= link_to '結帳', checkout_cart_path, class: 'button is-danger' unless current_cart.empty? %>